[package]
name = "lang_vm"
version = "0.1.0"
edition = "2021"


[workspace]
members = [
  "apps/lsp_server",
  "tree-sitter-langvm",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

