#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_SEMI = 3,
  anon_sym_fn = 4,
  anon_sym_while = 5,
  anon_sym_if = 6,
  anon_sym_else = 7,
  anon_sym_PERCENT = 8,
  anon_sym_STAR = 9,
  anon_sym_SLASH = 10,
  anon_sym_DASH = 11,
  anon_sym_PLUS = 12,
  anon_sym_EQ_EQ = 13,
  anon_sym_BANG_EQ = 14,
  anon_sym_LPAREN = 15,
  anon_sym_COMMA = 16,
  anon_sym_RPAREN = 17,
  anon_sym_EQ = 18,
  anon_sym_DQUOTE = 19,
  aux_sym__string_double_token1 = 20,
  anon_sym_SQUOTE = 21,
  aux_sym__string_single_token1 = 22,
  aux_sym_param_token1 = 23,
  sym__number_dec = 24,
  sym__number_oct = 25,
  sym__number_hex = 26,
  sym_comment = 27,
  sym_source_file = 28,
  sym_block = 29,
  sym_statement = 30,
  sym_function = 31,
  sym_while = 32,
  sym_choice = 33,
  sym__expression = 34,
  sym_binary_expression = 35,
  sym__noun = 36,
  sym_call = 37,
  sym_params = 38,
  sym_arguments = 39,
  sym__parenthesis = 40,
  sym_assignment = 41,
  sym_string = 42,
  sym__string_double = 43,
  sym__string_single = 44,
  sym_param = 45,
  sym_name = 46,
  sym_identifier = 47,
  sym_number = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_params_repeat1 = 50,
  aux_sym_arguments_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_fn] = "fn",
  [anon_sym_while] = "while",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_PERCENT] = "%",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__string_double_token1] = "_string_double_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__string_single_token1] = "_string_single_token1",
  [aux_sym_param_token1] = "param_token1",
  [sym__number_dec] = "_number_dec",
  [sym__number_oct] = "_number_oct",
  [sym__number_hex] = "_number_hex",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_function] = "function",
  [sym_while] = "while",
  [sym_choice] = "choice",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__noun] = "_noun",
  [sym_call] = "call",
  [sym_params] = "params",
  [sym_arguments] = "arguments",
  [sym__parenthesis] = "_parenthesis",
  [sym_assignment] = "assignment",
  [sym_string] = "string",
  [sym__string_double] = "_string_double",
  [sym__string_single] = "_string_single",
  [sym_param] = "param",
  [sym_name] = "name",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__string_double_token1] = aux_sym__string_double_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__string_single_token1] = aux_sym__string_single_token1,
  [aux_sym_param_token1] = aux_sym_param_token1,
  [sym__number_dec] = sym__number_dec,
  [sym__number_oct] = sym__number_oct,
  [sym__number_hex] = sym__number_hex,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_function] = sym_function,
  [sym_while] = sym_while,
  [sym_choice] = sym_choice,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__noun] = sym__noun,
  [sym_call] = sym_call,
  [sym_params] = sym_params,
  [sym_arguments] = sym_arguments,
  [sym__parenthesis] = sym__parenthesis,
  [sym_assignment] = sym_assignment,
  [sym_string] = sym_string,
  [sym__string_double] = sym__string_double,
  [sym__string_single] = sym__string_single,
  [sym_param] = sym_param,
  [sym_name] = sym_name,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_double_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_single_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__number_dec] = {
    .visible = false,
    .named = true,
  },
  [sym__number_oct] = {
    .visible = false,
    .named = true,
  },
  [sym__number_hex] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_choice] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__noun] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesis] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_double] = {
    .visible = false,
    .named = true,
  },
  [sym__string_single] = {
    .visible = false,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 9,
  [38] = 21,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '0') ADVANCE(53);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 'w') ADVANCE(45);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(53);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(55);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '0') ADVANCE(53);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 'w') ADVANCE(45);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(57);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == '"') ADVANCE(57);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'f') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'h') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'i') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'l') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'l') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'n') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 's') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__number_dec);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__number_oct);
      if (lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__number_oct);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__number_hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 40},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 33},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_param_token1] = ACTIONS(1),
    [sym__number_dec] = ACTIONS(1),
    [sym__number_oct] = ACTIONS(1),
    [sym__number_hex] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(65),
    [sym_block] = STATE(35),
    [sym_statement] = STATE(7),
    [sym_function] = STATE(35),
    [sym_while] = STATE(41),
    [sym_choice] = STATE(41),
    [sym__expression] = STATE(35),
    [sym_binary_expression] = STATE(35),
    [sym__noun] = STATE(35),
    [sym_call] = STATE(35),
    [sym__parenthesis] = STATE(35),
    [sym_assignment] = STATE(41),
    [sym_string] = STATE(35),
    [sym__string_double] = STATE(18),
    [sym__string_single] = STATE(18),
    [sym_name] = STATE(54),
    [sym_identifier] = STATE(27),
    [sym_number] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_param_token1] = ACTIONS(21),
    [sym__number_dec] = ACTIONS(23),
    [sym__number_oct] = ACTIONS(25),
    [sym__number_hex] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_block] = STATE(35),
    [sym_statement] = STATE(2),
    [sym_function] = STATE(35),
    [sym_while] = STATE(41),
    [sym_choice] = STATE(41),
    [sym__expression] = STATE(35),
    [sym_binary_expression] = STATE(35),
    [sym__noun] = STATE(35),
    [sym_call] = STATE(35),
    [sym__parenthesis] = STATE(35),
    [sym_assignment] = STATE(41),
    [sym_string] = STATE(35),
    [sym__string_double] = STATE(18),
    [sym__string_single] = STATE(18),
    [sym_name] = STATE(54),
    [sym_identifier] = STATE(27),
    [sym_number] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_fn] = ACTIONS(32),
    [anon_sym_while] = ACTIONS(35),
    [anon_sym_if] = ACTIONS(38),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_DQUOTE] = ACTIONS(44),
    [anon_sym_SQUOTE] = ACTIONS(47),
    [aux_sym_param_token1] = ACTIONS(50),
    [sym__number_dec] = ACTIONS(53),
    [sym__number_oct] = ACTIONS(56),
    [sym__number_hex] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_block] = STATE(35),
    [sym_statement] = STATE(6),
    [sym_function] = STATE(35),
    [sym_while] = STATE(41),
    [sym_choice] = STATE(41),
    [sym__expression] = STATE(35),
    [sym_binary_expression] = STATE(35),
    [sym__noun] = STATE(35),
    [sym_call] = STATE(35),
    [sym__parenthesis] = STATE(35),
    [sym_assignment] = STATE(41),
    [sym_string] = STATE(35),
    [sym__string_double] = STATE(18),
    [sym__string_single] = STATE(18),
    [sym_name] = STATE(54),
    [sym_identifier] = STATE(27),
    [sym_number] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_param_token1] = ACTIONS(21),
    [sym__number_dec] = ACTIONS(23),
    [sym__number_oct] = ACTIONS(25),
    [sym__number_hex] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_block] = STATE(35),
    [sym_statement] = STATE(2),
    [sym_function] = STATE(35),
    [sym_while] = STATE(41),
    [sym_choice] = STATE(41),
    [sym__expression] = STATE(35),
    [sym_binary_expression] = STATE(35),
    [sym__noun] = STATE(35),
    [sym_call] = STATE(35),
    [sym__parenthesis] = STATE(35),
    [sym_assignment] = STATE(41),
    [sym_string] = STATE(35),
    [sym__string_double] = STATE(18),
    [sym__string_single] = STATE(18),
    [sym_name] = STATE(54),
    [sym_identifier] = STATE(27),
    [sym_number] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_param_token1] = ACTIONS(21),
    [sym__number_dec] = ACTIONS(23),
    [sym__number_oct] = ACTIONS(25),
    [sym__number_hex] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_block] = STATE(35),
    [sym_statement] = STATE(4),
    [sym_function] = STATE(35),
    [sym_while] = STATE(41),
    [sym_choice] = STATE(41),
    [sym__expression] = STATE(35),
    [sym_binary_expression] = STATE(35),
    [sym__noun] = STATE(35),
    [sym_call] = STATE(35),
    [sym__parenthesis] = STATE(35),
    [sym_assignment] = STATE(41),
    [sym_string] = STATE(35),
    [sym__string_double] = STATE(18),
    [sym__string_single] = STATE(18),
    [sym_name] = STATE(54),
    [sym_identifier] = STATE(27),
    [sym_number] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_param_token1] = ACTIONS(21),
    [sym__number_dec] = ACTIONS(23),
    [sym__number_oct] = ACTIONS(25),
    [sym__number_hex] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_block] = STATE(35),
    [sym_statement] = STATE(2),
    [sym_function] = STATE(35),
    [sym_while] = STATE(41),
    [sym_choice] = STATE(41),
    [sym__expression] = STATE(35),
    [sym_binary_expression] = STATE(35),
    [sym__noun] = STATE(35),
    [sym_call] = STATE(35),
    [sym__parenthesis] = STATE(35),
    [sym_assignment] = STATE(41),
    [sym_string] = STATE(35),
    [sym__string_double] = STATE(18),
    [sym__string_single] = STATE(18),
    [sym_name] = STATE(54),
    [sym_identifier] = STATE(27),
    [sym_number] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(65),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_param_token1] = ACTIONS(21),
    [sym__number_dec] = ACTIONS(23),
    [sym__number_oct] = ACTIONS(25),
    [sym__number_hex] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [sym_block] = STATE(35),
    [sym_statement] = STATE(2),
    [sym_function] = STATE(35),
    [sym_while] = STATE(41),
    [sym_choice] = STATE(41),
    [sym__expression] = STATE(35),
    [sym_binary_expression] = STATE(35),
    [sym__noun] = STATE(35),
    [sym_call] = STATE(35),
    [sym__parenthesis] = STATE(35),
    [sym_assignment] = STATE(41),
    [sym_string] = STATE(35),
    [sym__string_double] = STATE(18),
    [sym__string_single] = STATE(18),
    [sym_name] = STATE(54),
    [sym_identifier] = STATE(27),
    [sym_number] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [aux_sym_param_token1] = ACTIONS(21),
    [sym__number_dec] = ACTIONS(23),
    [sym__number_oct] = ACTIONS(25),
    [sym__number_hex] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(71), 7,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      anon_sym_EQ,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(69), 16,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [34] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(75), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [65] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(79), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [96] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(83), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [127] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(87), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [158] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(91), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [189] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(95), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [220] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(43), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [271] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(101), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [302] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(105), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [333] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(109), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(113), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [395] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(117), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(121), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(125), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [488] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(127), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(125), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [527] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(127), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(125), 15,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [564] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(127), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(125), 16,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [597] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(34), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [645] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_EQ,
    ACTIONS(139), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(137), 15,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [677] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(22), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [725] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(25), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [773] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(24), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [821] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(23), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [869] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(44), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [917] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      aux_sym_param_token1,
    ACTIONS(25), 1,
      sym__number_oct,
    STATE(54), 1,
      sym_name,
    ACTIONS(23), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(18), 2,
      sym__string_double,
      sym__string_single,
    STATE(45), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [965] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(147), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(145), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1004] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(151), 1,
      anon_sym_SEMI,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(147), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(153), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(149), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1045] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_else,
    ACTIONS(157), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(155), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1070] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(75), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1093] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 6,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(121), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1116] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(161), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1138] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(165), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1160] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_SEMI,
    ACTIONS(153), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(149), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1184] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 5,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(169), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1205] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(147), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1235] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(147), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(177), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1260] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(147), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1284] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_params_repeat1,
  [1297] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_params_repeat1,
  [1310] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_arguments_repeat1,
  [1323] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_params_repeat1,
  [1336] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_arguments_repeat1,
  [1349] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 1,
      aux_sym_param_token1,
    STATE(46), 1,
      sym_param,
  [1362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_block,
  [1372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1380] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_arguments,
  [1390] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_block,
  [1400] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      aux_sym_param_token1,
    STATE(60), 1,
      sym_param,
  [1410] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    STATE(55), 1,
      sym_params,
  [1420] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
  [1430] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_block,
  [1440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym__parenthesis,
  [1458] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      aux_sym_param_token1,
    STATE(57), 1,
      sym_name,
  [1468] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym__parenthesis,
  [1478] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
  [1485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [1492] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
  [1499] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
  [1506] = 2,
    ACTIONS(217), 1,
      aux_sym__string_single_token1,
    ACTIONS(219), 1,
      sym_comment,
  [1513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_DQUOTE,
  [1520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_LBRACE,
  [1527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_SQUOTE,
  [1534] = 2,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(227), 1,
      aux_sym__string_double_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 34,
  [SMALL_STATE(10)] = 65,
  [SMALL_STATE(11)] = 96,
  [SMALL_STATE(12)] = 127,
  [SMALL_STATE(13)] = 158,
  [SMALL_STATE(14)] = 189,
  [SMALL_STATE(15)] = 220,
  [SMALL_STATE(16)] = 271,
  [SMALL_STATE(17)] = 302,
  [SMALL_STATE(18)] = 333,
  [SMALL_STATE(19)] = 364,
  [SMALL_STATE(20)] = 395,
  [SMALL_STATE(21)] = 426,
  [SMALL_STATE(22)] = 457,
  [SMALL_STATE(23)] = 488,
  [SMALL_STATE(24)] = 527,
  [SMALL_STATE(25)] = 564,
  [SMALL_STATE(26)] = 597,
  [SMALL_STATE(27)] = 645,
  [SMALL_STATE(28)] = 677,
  [SMALL_STATE(29)] = 725,
  [SMALL_STATE(30)] = 773,
  [SMALL_STATE(31)] = 821,
  [SMALL_STATE(32)] = 869,
  [SMALL_STATE(33)] = 917,
  [SMALL_STATE(34)] = 965,
  [SMALL_STATE(35)] = 1004,
  [SMALL_STATE(36)] = 1045,
  [SMALL_STATE(37)] = 1070,
  [SMALL_STATE(38)] = 1093,
  [SMALL_STATE(39)] = 1116,
  [SMALL_STATE(40)] = 1138,
  [SMALL_STATE(41)] = 1160,
  [SMALL_STATE(42)] = 1184,
  [SMALL_STATE(43)] = 1205,
  [SMALL_STATE(44)] = 1235,
  [SMALL_STATE(45)] = 1260,
  [SMALL_STATE(46)] = 1284,
  [SMALL_STATE(47)] = 1297,
  [SMALL_STATE(48)] = 1310,
  [SMALL_STATE(49)] = 1323,
  [SMALL_STATE(50)] = 1336,
  [SMALL_STATE(51)] = 1349,
  [SMALL_STATE(52)] = 1362,
  [SMALL_STATE(53)] = 1372,
  [SMALL_STATE(54)] = 1380,
  [SMALL_STATE(55)] = 1390,
  [SMALL_STATE(56)] = 1400,
  [SMALL_STATE(57)] = 1410,
  [SMALL_STATE(58)] = 1420,
  [SMALL_STATE(59)] = 1430,
  [SMALL_STATE(60)] = 1440,
  [SMALL_STATE(61)] = 1448,
  [SMALL_STATE(62)] = 1458,
  [SMALL_STATE(63)] = 1468,
  [SMALL_STATE(64)] = 1478,
  [SMALL_STATE(65)] = 1485,
  [SMALL_STATE(66)] = 1492,
  [SMALL_STATE(67)] = 1499,
  [SMALL_STATE(68)] = 1506,
  [SMALL_STATE(69)] = 1513,
  [SMALL_STATE(70)] = 1520,
  [SMALL_STATE(71)] = 1527,
  [SMALL_STATE(72)] = 1534,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(72),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(68),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 4),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesis, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesis, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_double, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_double, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_single, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_single, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__noun, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__noun, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 3),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 3),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while, 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 5),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 5),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2), SHIFT_REPEAT(56),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(32),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 4),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_loom(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
