#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_SEMI = 3,
  anon_sym_let = 4,
  anon_sym_EQ = 5,
  anon_sym_return = 6,
  anon_sym_fn = 7,
  anon_sym_while = 8,
  anon_sym_if = 9,
  anon_sym_else = 10,
  anon_sym_PERCENT = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_DASH = 14,
  anon_sym_PLUS = 15,
  anon_sym_EQ_EQ = 16,
  anon_sym_BANG_EQ = 17,
  anon_sym_LPAREN = 18,
  anon_sym_COMMA = 19,
  anon_sym_RPAREN = 20,
  anon_sym_DQUOTE = 21,
  aux_sym__string_double_token1 = 22,
  anon_sym_SQUOTE = 23,
  aux_sym__string_single_token1 = 24,
  aux_sym_param_token1 = 25,
  sym__number_dec = 26,
  sym__number_oct = 27,
  sym__number_hex = 28,
  sym_comment = 29,
  sym_source_file = 30,
  sym_block = 31,
  sym_statement = 32,
  sym_define = 33,
  sym_return = 34,
  sym_function = 35,
  sym_while = 36,
  sym_choice = 37,
  sym__expression = 38,
  sym_binary_expression = 39,
  sym__noun = 40,
  sym_call = 41,
  sym_params = 42,
  sym_arguments = 43,
  sym__parenthesis = 44,
  sym_assignment = 45,
  sym_string = 46,
  sym__string_double = 47,
  sym__string_single = 48,
  sym_param = 49,
  sym_name = 50,
  sym_identifier = 51,
  sym_number = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_params_repeat1 = 54,
  aux_sym_arguments_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_fn] = "fn",
  [anon_sym_while] = "while",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_PERCENT] = "%",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__string_double_token1] = "_string_double_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__string_single_token1] = "_string_single_token1",
  [aux_sym_param_token1] = "param_token1",
  [sym__number_dec] = "_number_dec",
  [sym__number_oct] = "_number_oct",
  [sym__number_hex] = "_number_hex",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_define] = "define",
  [sym_return] = "return",
  [sym_function] = "function",
  [sym_while] = "while",
  [sym_choice] = "choice",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__noun] = "_noun",
  [sym_call] = "call",
  [sym_params] = "params",
  [sym_arguments] = "arguments",
  [sym__parenthesis] = "_parenthesis",
  [sym_assignment] = "assignment",
  [sym_string] = "string",
  [sym__string_double] = "_string_double",
  [sym__string_single] = "_string_single",
  [sym_param] = "param",
  [sym_name] = "name",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__string_double_token1] = aux_sym__string_double_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__string_single_token1] = aux_sym__string_single_token1,
  [aux_sym_param_token1] = aux_sym_param_token1,
  [sym__number_dec] = sym__number_dec,
  [sym__number_oct] = sym__number_oct,
  [sym__number_hex] = sym__number_hex,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_define] = sym_define,
  [sym_return] = sym_return,
  [sym_function] = sym_function,
  [sym_while] = sym_while,
  [sym_choice] = sym_choice,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__noun] = sym__noun,
  [sym_call] = sym_call,
  [sym_params] = sym_params,
  [sym_arguments] = sym_arguments,
  [sym__parenthesis] = sym__parenthesis,
  [sym_assignment] = sym_assignment,
  [sym_string] = sym_string,
  [sym__string_double] = sym__string_double,
  [sym__string_single] = sym__string_single,
  [sym_param] = sym_param,
  [sym_name] = sym_name,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_double_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_single_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__number_dec] = {
    .visible = false,
    .named = true,
  },
  [sym__number_oct] = {
    .visible = false,
    .named = true,
  },
  [sym__number_hex] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_define] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_choice] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__noun] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesis] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_double] = {
    .visible = false,
    .named = true,
  },
  [sym__string_single] = {
    .visible = false,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 22,
  [41] = 41,
  [42] = 42,
  [43] = 9,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '%') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(24);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'l') ADVANCE(44);
      if (lookahead == 'r') ADVANCE(47);
      if (lookahead == 'w') ADVANCE(49);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == 'f') ADVANCE(53);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(66);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '%') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(24);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'l') ADVANCE(44);
      if (lookahead == 'r') ADVANCE(47);
      if (lookahead == 'w') ADVANCE(49);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(66);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '"') ADVANCE(66);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\n') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'f') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'h') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'l') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'l') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'n') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'n') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 's') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 't') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'u') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__number_dec);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__number_oct);
      if (lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__number_oct);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__number_hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 42},
  [79] = {.lex_state = 35},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_param_token1] = ACTIONS(1),
    [sym__number_dec] = ACTIONS(1),
    [sym__number_oct] = ACTIONS(1),
    [sym__number_hex] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(76),
    [sym_block] = STATE(27),
    [sym_statement] = STATE(3),
    [sym_define] = STATE(47),
    [sym_return] = STATE(47),
    [sym_function] = STATE(27),
    [sym_while] = STATE(47),
    [sym_choice] = STATE(47),
    [sym__expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__noun] = STATE(27),
    [sym_call] = STATE(27),
    [sym__parenthesis] = STATE(27),
    [sym_assignment] = STATE(47),
    [sym_string] = STATE(27),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(67),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [aux_sym_param_token1] = ACTIONS(25),
    [sym__number_dec] = ACTIONS(27),
    [sym__number_oct] = ACTIONS(29),
    [sym__number_hex] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_block] = STATE(27),
    [sym_statement] = STATE(2),
    [sym_define] = STATE(47),
    [sym_return] = STATE(47),
    [sym_function] = STATE(27),
    [sym_while] = STATE(47),
    [sym_choice] = STATE(47),
    [sym__expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__noun] = STATE(27),
    [sym_call] = STATE(27),
    [sym__parenthesis] = STATE(27),
    [sym_assignment] = STATE(47),
    [sym_string] = STATE(27),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(67),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_let] = ACTIONS(36),
    [anon_sym_return] = ACTIONS(39),
    [anon_sym_fn] = ACTIONS(42),
    [anon_sym_while] = ACTIONS(45),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(54),
    [anon_sym_SQUOTE] = ACTIONS(57),
    [aux_sym_param_token1] = ACTIONS(60),
    [sym__number_dec] = ACTIONS(63),
    [sym__number_oct] = ACTIONS(66),
    [sym__number_hex] = ACTIONS(63),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_block] = STATE(27),
    [sym_statement] = STATE(2),
    [sym_define] = STATE(47),
    [sym_return] = STATE(47),
    [sym_function] = STATE(27),
    [sym_while] = STATE(47),
    [sym_choice] = STATE(47),
    [sym__expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__noun] = STATE(27),
    [sym_call] = STATE(27),
    [sym__parenthesis] = STATE(27),
    [sym_assignment] = STATE(47),
    [sym_string] = STATE(27),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(67),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [aux_sym_param_token1] = ACTIONS(25),
    [sym__number_dec] = ACTIONS(27),
    [sym__number_oct] = ACTIONS(29),
    [sym__number_hex] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_block] = STATE(27),
    [sym_statement] = STATE(7),
    [sym_define] = STATE(47),
    [sym_return] = STATE(47),
    [sym_function] = STATE(27),
    [sym_while] = STATE(47),
    [sym_choice] = STATE(47),
    [sym__expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__noun] = STATE(27),
    [sym_call] = STATE(27),
    [sym__parenthesis] = STATE(27),
    [sym_assignment] = STATE(47),
    [sym_string] = STATE(27),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(67),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(71),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [aux_sym_param_token1] = ACTIONS(25),
    [sym__number_dec] = ACTIONS(27),
    [sym__number_oct] = ACTIONS(29),
    [sym__number_hex] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_block] = STATE(27),
    [sym_statement] = STATE(2),
    [sym_define] = STATE(47),
    [sym_return] = STATE(47),
    [sym_function] = STATE(27),
    [sym_while] = STATE(47),
    [sym_choice] = STATE(47),
    [sym__expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__noun] = STATE(27),
    [sym_call] = STATE(27),
    [sym__parenthesis] = STATE(27),
    [sym_assignment] = STATE(47),
    [sym_string] = STATE(27),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(67),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [aux_sym_param_token1] = ACTIONS(25),
    [sym__number_dec] = ACTIONS(27),
    [sym__number_oct] = ACTIONS(29),
    [sym__number_hex] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_block] = STATE(27),
    [sym_statement] = STATE(5),
    [sym_define] = STATE(47),
    [sym_return] = STATE(47),
    [sym_function] = STATE(27),
    [sym_while] = STATE(47),
    [sym_choice] = STATE(47),
    [sym__expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__noun] = STATE(27),
    [sym_call] = STATE(27),
    [sym__parenthesis] = STATE(27),
    [sym_assignment] = STATE(47),
    [sym_string] = STATE(27),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(67),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [aux_sym_param_token1] = ACTIONS(25),
    [sym__number_dec] = ACTIONS(27),
    [sym__number_oct] = ACTIONS(29),
    [sym__number_hex] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [sym_block] = STATE(27),
    [sym_statement] = STATE(2),
    [sym_define] = STATE(47),
    [sym_return] = STATE(47),
    [sym_function] = STATE(27),
    [sym_while] = STATE(47),
    [sym_choice] = STATE(47),
    [sym__expression] = STATE(27),
    [sym_binary_expression] = STATE(27),
    [sym__noun] = STATE(27),
    [sym_call] = STATE(27),
    [sym__parenthesis] = STATE(27),
    [sym_assignment] = STATE(47),
    [sym_string] = STATE(27),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(67),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [aux_sym_param_token1] = ACTIONS(25),
    [sym__number_dec] = ACTIONS(27),
    [sym__number_oct] = ACTIONS(29),
    [sym__number_hex] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 9,
      anon_sym_let,
      anon_sym_EQ,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(79), 16,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [36] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(85), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [69] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(89), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(93), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [135] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(99), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [176] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(99), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(97), 15,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [215] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(99), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(97), 16,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(109), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(97), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(113), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(117), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [382] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(121), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(125), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(129), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [481] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(133), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(137), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [547] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(141), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [580] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_EQ,
    ACTIONS(147), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(145), 15,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [614] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(153), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(151), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [655] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(161), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(157), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [698] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(165), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(163), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [739] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(49), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [790] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(171), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(169), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [831] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(14), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [879] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(26), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [927] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(51), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [975] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(16), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1023] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(13), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1071] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(12), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1119] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(30), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1167] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(28), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1215] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      aux_sym_param_token1,
    ACTIONS(29), 1,
      sym__number_oct,
    STATE(67), 1,
      sym_name,
    ACTIONS(27), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(50), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1263] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(133), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1288] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_EQ,
    ACTIONS(175), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(173), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(85), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1365] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_else,
    ACTIONS(181), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(179), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1392] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(185), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1416] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(189), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1440] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    ACTIONS(161), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(157), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1466] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(193), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1489] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1519] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1544] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1568] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_params_repeat1,
  [1581] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    ACTIONS(212), 1,
      aux_sym_param_token1,
    STATE(57), 1,
      sym_param,
  [1594] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_arguments_repeat1,
  [1607] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_arguments_repeat1,
  [1620] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_params_repeat1,
  [1633] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_params_repeat1,
  [1646] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
  [1656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
    STATE(64), 1,
      sym_params,
  [1666] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym__parenthesis,
  [1676] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      aux_sym_param_token1,
    STATE(59), 1,
      sym_name,
  [1686] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_block,
  [1696] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(70), 1,
      sym__parenthesis,
  [1706] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_block,
  [1716] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      aux_sym_param_token1,
    STATE(41), 1,
      sym_identifier,
  [1726] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      aux_sym_param_token1,
    STATE(68), 1,
      sym_param,
  [1736] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_arguments,
  [1746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1754] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1762] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_block,
  [1772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_DQUOTE,
  [1779] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
  [1786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_LBRACE,
  [1793] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
  [1800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_SQUOTE,
  [1807] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
  [1814] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LBRACE,
  [1821] = 2,
    ACTIONS(249), 1,
      aux_sym__string_single_token1,
    ACTIONS(251), 1,
      sym_comment,
  [1828] = 2,
    ACTIONS(251), 1,
      sym_comment,
    ACTIONS(253), 1,
      aux_sym__string_double_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 36,
  [SMALL_STATE(10)] = 69,
  [SMALL_STATE(11)] = 102,
  [SMALL_STATE(12)] = 135,
  [SMALL_STATE(13)] = 176,
  [SMALL_STATE(14)] = 215,
  [SMALL_STATE(15)] = 250,
  [SMALL_STATE(16)] = 283,
  [SMALL_STATE(17)] = 316,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 382,
  [SMALL_STATE(20)] = 415,
  [SMALL_STATE(21)] = 448,
  [SMALL_STATE(22)] = 481,
  [SMALL_STATE(23)] = 514,
  [SMALL_STATE(24)] = 547,
  [SMALL_STATE(25)] = 580,
  [SMALL_STATE(26)] = 614,
  [SMALL_STATE(27)] = 655,
  [SMALL_STATE(28)] = 698,
  [SMALL_STATE(29)] = 739,
  [SMALL_STATE(30)] = 790,
  [SMALL_STATE(31)] = 831,
  [SMALL_STATE(32)] = 879,
  [SMALL_STATE(33)] = 927,
  [SMALL_STATE(34)] = 975,
  [SMALL_STATE(35)] = 1023,
  [SMALL_STATE(36)] = 1071,
  [SMALL_STATE(37)] = 1119,
  [SMALL_STATE(38)] = 1167,
  [SMALL_STATE(39)] = 1215,
  [SMALL_STATE(40)] = 1263,
  [SMALL_STATE(41)] = 1288,
  [SMALL_STATE(42)] = 1315,
  [SMALL_STATE(43)] = 1340,
  [SMALL_STATE(44)] = 1365,
  [SMALL_STATE(45)] = 1392,
  [SMALL_STATE(46)] = 1416,
  [SMALL_STATE(47)] = 1440,
  [SMALL_STATE(48)] = 1466,
  [SMALL_STATE(49)] = 1489,
  [SMALL_STATE(50)] = 1519,
  [SMALL_STATE(51)] = 1544,
  [SMALL_STATE(52)] = 1568,
  [SMALL_STATE(53)] = 1581,
  [SMALL_STATE(54)] = 1594,
  [SMALL_STATE(55)] = 1607,
  [SMALL_STATE(56)] = 1620,
  [SMALL_STATE(57)] = 1633,
  [SMALL_STATE(58)] = 1646,
  [SMALL_STATE(59)] = 1656,
  [SMALL_STATE(60)] = 1666,
  [SMALL_STATE(61)] = 1676,
  [SMALL_STATE(62)] = 1686,
  [SMALL_STATE(63)] = 1696,
  [SMALL_STATE(64)] = 1706,
  [SMALL_STATE(65)] = 1716,
  [SMALL_STATE(66)] = 1726,
  [SMALL_STATE(67)] = 1736,
  [SMALL_STATE(68)] = 1746,
  [SMALL_STATE(69)] = 1754,
  [SMALL_STATE(70)] = 1762,
  [SMALL_STATE(71)] = 1772,
  [SMALL_STATE(72)] = 1779,
  [SMALL_STATE(73)] = 1786,
  [SMALL_STATE(74)] = 1793,
  [SMALL_STATE(75)] = 1800,
  [SMALL_STATE(76)] = 1807,
  [SMALL_STATE(77)] = 1814,
  [SMALL_STATE(78)] = 1821,
  [SMALL_STATE(79)] = 1828,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(65),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(32),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(60),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(79),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(78),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesis, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesis, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_single, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_single, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_double, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_double, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__noun, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__noun, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define, 4),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define, 4),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 3),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 5),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 5),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 3),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2), SHIFT_REPEAT(66),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(39),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 4),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [245] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_loom(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
