#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_SEMI = 3,
  anon_sym_return = 4,
  anon_sym_fn = 5,
  anon_sym_while = 6,
  anon_sym_if = 7,
  anon_sym_else = 8,
  anon_sym_PERCENT = 9,
  anon_sym_STAR = 10,
  anon_sym_SLASH = 11,
  anon_sym_DASH = 12,
  anon_sym_PLUS = 13,
  anon_sym_EQ_EQ = 14,
  anon_sym_BANG_EQ = 15,
  anon_sym_LPAREN = 16,
  anon_sym_COMMA = 17,
  anon_sym_RPAREN = 18,
  anon_sym_EQ = 19,
  anon_sym_DQUOTE = 20,
  aux_sym__string_double_token1 = 21,
  anon_sym_SQUOTE = 22,
  aux_sym__string_single_token1 = 23,
  aux_sym_param_token1 = 24,
  sym__number_dec = 25,
  sym__number_oct = 26,
  sym__number_hex = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym_block = 30,
  sym_statement = 31,
  sym_return = 32,
  sym_function = 33,
  sym_while = 34,
  sym_choice = 35,
  sym__expression = 36,
  sym_binary_expression = 37,
  sym__noun = 38,
  sym_call = 39,
  sym_params = 40,
  sym_arguments = 41,
  sym__parenthesis = 42,
  sym_assignment = 43,
  sym_string = 44,
  sym__string_double = 45,
  sym__string_single = 46,
  sym_param = 47,
  sym_name = 48,
  sym_identifier = 49,
  sym_number = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_params_repeat1 = 52,
  aux_sym_arguments_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_return] = "return",
  [anon_sym_fn] = "fn",
  [anon_sym_while] = "while",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_PERCENT] = "%",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__string_double_token1] = "_string_double_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__string_single_token1] = "_string_single_token1",
  [aux_sym_param_token1] = "param_token1",
  [sym__number_dec] = "_number_dec",
  [sym__number_oct] = "_number_oct",
  [sym__number_hex] = "_number_hex",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_return] = "return",
  [sym_function] = "function",
  [sym_while] = "while",
  [sym_choice] = "choice",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__noun] = "_noun",
  [sym_call] = "call",
  [sym_params] = "params",
  [sym_arguments] = "arguments",
  [sym__parenthesis] = "_parenthesis",
  [sym_assignment] = "assignment",
  [sym_string] = "string",
  [sym__string_double] = "_string_double",
  [sym__string_single] = "_string_single",
  [sym_param] = "param",
  [sym_name] = "name",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__string_double_token1] = aux_sym__string_double_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__string_single_token1] = aux_sym__string_single_token1,
  [aux_sym_param_token1] = aux_sym_param_token1,
  [sym__number_dec] = sym__number_dec,
  [sym__number_oct] = sym__number_oct,
  [sym__number_hex] = sym__number_hex,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_return] = sym_return,
  [sym_function] = sym_function,
  [sym_while] = sym_while,
  [sym_choice] = sym_choice,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__noun] = sym__noun,
  [sym_call] = sym_call,
  [sym_params] = sym_params,
  [sym_arguments] = sym_arguments,
  [sym__parenthesis] = sym__parenthesis,
  [sym_assignment] = sym_assignment,
  [sym_string] = sym_string,
  [sym__string_double] = sym__string_double,
  [sym__string_single] = sym__string_single,
  [sym_param] = sym_param,
  [sym_name] = sym_name,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_double_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_single_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__number_dec] = {
    .visible = false,
    .named = true,
  },
  [sym__number_oct] = {
    .visible = false,
    .named = true,
  },
  [sym__number_hex] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_choice] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__noun] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesis] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_double] = {
    .visible = false,
    .named = true,
  },
  [sym__string_single] = {
    .visible = false,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 24,
  [40] = 22,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '\'') ADVANCE(36);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '0') ADVANCE(59);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == 'f') ADVANCE(51);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'r') ADVANCE(43);
      if (lookahead == 'w') ADVANCE(47);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\'') ADVANCE(36);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(59);
      if (lookahead == 'f') ADVANCE(51);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(62);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '\'') ADVANCE(36);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '0') ADVANCE(59);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == 'f') ADVANCE(51);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'r') ADVANCE(43);
      if (lookahead == 'w') ADVANCE(47);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(63);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '"') ADVANCE(63);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__string_double_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__string_single_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'f') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'h') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'i') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'l') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'l') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'n') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'n') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'r') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 's') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 't') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (lookahead == 'u') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_param_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__number_dec);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__number_oct);
      if (lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__number_oct);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__number_hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 41},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 34},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_param_token1] = ACTIONS(1),
    [sym__number_dec] = ACTIONS(1),
    [sym__number_oct] = ACTIONS(1),
    [sym__number_hex] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(67),
    [sym_block] = STATE(29),
    [sym_statement] = STATE(3),
    [sym_return] = STATE(43),
    [sym_function] = STATE(29),
    [sym_while] = STATE(43),
    [sym_choice] = STATE(43),
    [sym__expression] = STATE(29),
    [sym_binary_expression] = STATE(29),
    [sym__noun] = STATE(29),
    [sym_call] = STATE(29),
    [sym__parenthesis] = STATE(29),
    [sym_assignment] = STATE(43),
    [sym_string] = STATE(29),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(56),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [aux_sym_param_token1] = ACTIONS(23),
    [sym__number_dec] = ACTIONS(25),
    [sym__number_oct] = ACTIONS(27),
    [sym__number_hex] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_block] = STATE(29),
    [sym_statement] = STATE(2),
    [sym_return] = STATE(43),
    [sym_function] = STATE(29),
    [sym_while] = STATE(43),
    [sym_choice] = STATE(43),
    [sym__expression] = STATE(29),
    [sym_binary_expression] = STATE(29),
    [sym__noun] = STATE(29),
    [sym_call] = STATE(29),
    [sym__parenthesis] = STATE(29),
    [sym_assignment] = STATE(43),
    [sym_string] = STATE(29),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(56),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_return] = ACTIONS(34),
    [anon_sym_fn] = ACTIONS(37),
    [anon_sym_while] = ACTIONS(40),
    [anon_sym_if] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(52),
    [aux_sym_param_token1] = ACTIONS(55),
    [sym__number_dec] = ACTIONS(58),
    [sym__number_oct] = ACTIONS(61),
    [sym__number_hex] = ACTIONS(58),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_block] = STATE(29),
    [sym_statement] = STATE(2),
    [sym_return] = STATE(43),
    [sym_function] = STATE(29),
    [sym_while] = STATE(43),
    [sym_choice] = STATE(43),
    [sym__expression] = STATE(29),
    [sym_binary_expression] = STATE(29),
    [sym__noun] = STATE(29),
    [sym_call] = STATE(29),
    [sym__parenthesis] = STATE(29),
    [sym_assignment] = STATE(43),
    [sym_string] = STATE(29),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(56),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [aux_sym_param_token1] = ACTIONS(23),
    [sym__number_dec] = ACTIONS(25),
    [sym__number_oct] = ACTIONS(27),
    [sym__number_hex] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_block] = STATE(29),
    [sym_statement] = STATE(7),
    [sym_return] = STATE(43),
    [sym_function] = STATE(29),
    [sym_while] = STATE(43),
    [sym_choice] = STATE(43),
    [sym__expression] = STATE(29),
    [sym_binary_expression] = STATE(29),
    [sym__noun] = STATE(29),
    [sym_call] = STATE(29),
    [sym__parenthesis] = STATE(29),
    [sym_assignment] = STATE(43),
    [sym_string] = STATE(29),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(56),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(66),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [aux_sym_param_token1] = ACTIONS(23),
    [sym__number_dec] = ACTIONS(25),
    [sym__number_oct] = ACTIONS(27),
    [sym__number_hex] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_block] = STATE(29),
    [sym_statement] = STATE(2),
    [sym_return] = STATE(43),
    [sym_function] = STATE(29),
    [sym_while] = STATE(43),
    [sym_choice] = STATE(43),
    [sym__expression] = STATE(29),
    [sym_binary_expression] = STATE(29),
    [sym__noun] = STATE(29),
    [sym_call] = STATE(29),
    [sym__parenthesis] = STATE(29),
    [sym_assignment] = STATE(43),
    [sym_string] = STATE(29),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(56),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [aux_sym_param_token1] = ACTIONS(23),
    [sym__number_dec] = ACTIONS(25),
    [sym__number_oct] = ACTIONS(27),
    [sym__number_hex] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_block] = STATE(29),
    [sym_statement] = STATE(5),
    [sym_return] = STATE(43),
    [sym_function] = STATE(29),
    [sym_while] = STATE(43),
    [sym_choice] = STATE(43),
    [sym__expression] = STATE(29),
    [sym_binary_expression] = STATE(29),
    [sym__noun] = STATE(29),
    [sym_call] = STATE(29),
    [sym__parenthesis] = STATE(29),
    [sym_assignment] = STATE(43),
    [sym_string] = STATE(29),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(56),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [aux_sym_param_token1] = ACTIONS(23),
    [sym__number_dec] = ACTIONS(25),
    [sym__number_oct] = ACTIONS(27),
    [sym__number_hex] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [sym_block] = STATE(29),
    [sym_statement] = STATE(2),
    [sym_return] = STATE(43),
    [sym_function] = STATE(29),
    [sym_while] = STATE(43),
    [sym_choice] = STATE(43),
    [sym__expression] = STATE(29),
    [sym_binary_expression] = STATE(29),
    [sym__noun] = STATE(29),
    [sym_call] = STATE(29),
    [sym__parenthesis] = STATE(29),
    [sym_assignment] = STATE(43),
    [sym_string] = STATE(29),
    [sym__string_double] = STATE(19),
    [sym__string_single] = STATE(19),
    [sym_name] = STATE(56),
    [sym_identifier] = STATE(25),
    [sym_number] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [aux_sym_param_token1] = ACTIONS(23),
    [sym__number_dec] = ACTIONS(25),
    [sym__number_oct] = ACTIONS(27),
    [sym__number_hex] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 8,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      anon_sym_EQ,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(74), 16,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [35] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(80), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [67] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(84), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [99] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(88), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [131] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(92), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [163] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(96), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [195] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(100), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(104), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [259] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(108), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(112), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [323] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(116), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(120), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [387] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(118), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(116), 16,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [421] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(118), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(116), 15,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [459] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(130), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [491] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(118), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(116), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(136), 17,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [563] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_EQ,
    ACTIONS(142), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_SLASH,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(140), 15,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [596] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(45), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [647] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(150), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(148), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [687] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(154), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [727] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(160), 1,
      anon_sym_SEMI,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(162), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(158), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [769] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(46), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [817] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(47), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [865] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(27), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [913] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(18), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [961] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(20), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1009] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(21), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1057] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(23), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1105] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      aux_sym_param_token1,
    ACTIONS(27), 1,
      sym__number_oct,
    STATE(56), 1,
      sym_name,
    ACTIONS(25), 2,
      sym__number_dec,
      sym__number_hex,
    STATE(19), 2,
      sym__string_double,
      sym__string_single,
    STATE(28), 10,
      sym_block,
      sym_function,
      sym__expression,
      sym_binary_expression,
      sym__noun,
      sym_call,
      sym__parenthesis,
      sym_string,
      sym_identifier,
      sym_number,
  [1153] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_else,
    ACTIONS(166), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(164), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1179] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(136), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1203] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 7,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(130), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(170), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(174), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1273] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_SEMI,
    ACTIONS(162), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(158), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 6,
      anon_sym_return,
      anon_sym_fn,
      anon_sym_while,
      anon_sym_if,
      aux_sym_param_token1,
      sym__number_oct,
    ACTIONS(178), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__number_dec,
      sym__number_hex,
  [1320] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1350] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(186), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1375] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PERCENT,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1399] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_params_repeat1,
  [1412] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_params_repeat1,
  [1425] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_arguments_repeat1,
  [1438] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_params_repeat1,
  [1451] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_arguments_repeat1,
  [1464] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    ACTIONS(208), 1,
      aux_sym_param_token1,
    STATE(48), 1,
      sym_param,
  [1477] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_block,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1495] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_arguments,
  [1505] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block,
  [1515] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_param_token1,
    STATE(62), 1,
      sym_param,
  [1525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    STATE(57), 1,
      sym_params,
  [1535] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
  [1545] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_block,
  [1555] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(61), 1,
      sym__parenthesis,
  [1573] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(60), 1,
      sym__parenthesis,
  [1583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      aux_sym_param_token1,
    STATE(59), 1,
      sym_name,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_LBRACE,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
  [1607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
  [1614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
  [1621] = 2,
    ACTIONS(226), 1,
      aux_sym__string_single_token1,
    ACTIONS(228), 1,
      sym_comment,
  [1628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
  [1635] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
  [1642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_SQUOTE,
  [1649] = 2,
    ACTIONS(228), 1,
      sym_comment,
    ACTIONS(236), 1,
      aux_sym__string_double_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 35,
  [SMALL_STATE(10)] = 67,
  [SMALL_STATE(11)] = 99,
  [SMALL_STATE(12)] = 131,
  [SMALL_STATE(13)] = 163,
  [SMALL_STATE(14)] = 195,
  [SMALL_STATE(15)] = 227,
  [SMALL_STATE(16)] = 259,
  [SMALL_STATE(17)] = 291,
  [SMALL_STATE(18)] = 323,
  [SMALL_STATE(19)] = 355,
  [SMALL_STATE(20)] = 387,
  [SMALL_STATE(21)] = 421,
  [SMALL_STATE(22)] = 459,
  [SMALL_STATE(23)] = 491,
  [SMALL_STATE(24)] = 531,
  [SMALL_STATE(25)] = 563,
  [SMALL_STATE(26)] = 596,
  [SMALL_STATE(27)] = 647,
  [SMALL_STATE(28)] = 687,
  [SMALL_STATE(29)] = 727,
  [SMALL_STATE(30)] = 769,
  [SMALL_STATE(31)] = 817,
  [SMALL_STATE(32)] = 865,
  [SMALL_STATE(33)] = 913,
  [SMALL_STATE(34)] = 961,
  [SMALL_STATE(35)] = 1009,
  [SMALL_STATE(36)] = 1057,
  [SMALL_STATE(37)] = 1105,
  [SMALL_STATE(38)] = 1153,
  [SMALL_STATE(39)] = 1179,
  [SMALL_STATE(40)] = 1203,
  [SMALL_STATE(41)] = 1227,
  [SMALL_STATE(42)] = 1250,
  [SMALL_STATE(43)] = 1273,
  [SMALL_STATE(44)] = 1298,
  [SMALL_STATE(45)] = 1320,
  [SMALL_STATE(46)] = 1350,
  [SMALL_STATE(47)] = 1375,
  [SMALL_STATE(48)] = 1399,
  [SMALL_STATE(49)] = 1412,
  [SMALL_STATE(50)] = 1425,
  [SMALL_STATE(51)] = 1438,
  [SMALL_STATE(52)] = 1451,
  [SMALL_STATE(53)] = 1464,
  [SMALL_STATE(54)] = 1477,
  [SMALL_STATE(55)] = 1487,
  [SMALL_STATE(56)] = 1495,
  [SMALL_STATE(57)] = 1505,
  [SMALL_STATE(58)] = 1515,
  [SMALL_STATE(59)] = 1525,
  [SMALL_STATE(60)] = 1535,
  [SMALL_STATE(61)] = 1545,
  [SMALL_STATE(62)] = 1555,
  [SMALL_STATE(63)] = 1563,
  [SMALL_STATE(64)] = 1573,
  [SMALL_STATE(65)] = 1583,
  [SMALL_STATE(66)] = 1593,
  [SMALL_STATE(67)] = 1600,
  [SMALL_STATE(68)] = 1607,
  [SMALL_STATE(69)] = 1614,
  [SMALL_STATE(70)] = 1621,
  [SMALL_STATE(71)] = 1628,
  [SMALL_STATE(72)] = 1635,
  [SMALL_STATE(73)] = 1642,
  [SMALL_STATE(74)] = 1649,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(32),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(65),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(70),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesis, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesis, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_double, 3),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_double, 3),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 4),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_single, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_single, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__noun, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__noun, 1),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 3),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 3),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 3),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 5),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 5),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2), SHIFT_REPEAT(58),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(30),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2),
  [222] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 4),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_loom(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
