[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[lib]
tests = true
path = "src/lib.rs"
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
